version: '3'

services:
  criptolab:
    build: .
    container_name: criptolab
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_APP=src/main.py
      - FLASK_RUN_HOST=0.0.0.0
    command: python src/main.py
    restart: unless-stopped

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: mensajeria-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - SECRET_KEY=supersecretkey
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - BACKEND_CORS_ORIGINS=["http://localhost:8080"]
    volumes:
      - ./api:/app
      - ./api/certs:/app/certs
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mensajeria-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: unless-stopped 