version: '3'

services:
  criptolab:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: criptolab
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - ./docs:/app/docs
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_APP=src/main.py
      - FLASK_RUN_HOST=0.0.0.0
      - PYTHONPATH=/app:/app/src
    command: python src/main.py
    restart: unless-stopped 